#!/usr/bin/python3
import os 
import requests
import subprocess
from bs4 import BeautifulSoup
from termcolor import colored

a='''
     .____    .__        __    _______________  ___ _____  _________
     |    |   |__| ____ |  | __\_   _____/\   \/  // ____\/   _____/
     |    |   |  |/    \|  |/ / |    __)_  \     /\   __\ \_____  \ 
     |    |___|  |   |  \    <  |        \ /     \ |  |   /        |
     |_______ \__|___|  /__|_ \/_______  //___/\  \|__|  /_______  /
             \/       \/     \/        \/       \_/              \/ 

	   ############>Developed by EntityNetwork<############ 
'''
os.system('clear')
print(colored(a, 'magenta'))

url = input(colored("[*] Enter the website URL: ", 'green'))
os.system('clear')
print(colored(a, 'magenta'))
action = input(colored("[*] What do you want to do? \n[1] Extract links\n[2] Find parameters\n[3] Enumerate directories\n[4] Enumerate subdomains\n => ", 'cyan'))

if action == "1":
    os.system('clear')
    print(colored("[*] Extracting links...\n", 'red'))
    response = requests.get(url)
    soup = BeautifulSoup(response.text, 'html.parser')
    links = soup.find_all('a')
    for link in links:
        print(colored(link.get('href'), 'green'))

elif action == "2":
    os.system('clear')
    print(colored("[*] Finding parameters...\n", 'red'))
    response = requests.get(url)
    soup = BeautifulSoup(response.text, 'html.parser')
    forms = soup.find_all('form')
    for form in forms:
        inputs = form.find_all('input')
        for inp in inputs:
            print(colored(inp.get('name'), 'green'))

elif action == "3":
    os.system('clear')
    print(colored("[*] Enumerating directories...\n", 'red'))
    dirb_cmd = "dirb " + url
    dirb_output = subprocess.check_output(dirb_cmd, shell=True)
    print(colored(dirb_output.decode(), 'green'))

elif action == "4":
    os.system('clear')
    print(colored("[*] Performing subdomain enumeration...", 'red'))
    domain = input("[!] input your domain : ")
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0"
    }
    response = requests.get(f"https://api.hackertarget.com/dnslookup/?q={domain}", headers=headers)
    if response.status_code != 200:
        print(colored("[!] Failed to enumerate subdomains.", 'red'))
        exit(1)
    subdomains = response.text.split("\n")
    for subdomain in subdomains:
        if subdomain.strip() == "":
            continue
        print(colored(subdomain.strip(), 'green'))

else:
    print(colored("[!] Invalid input. Please enter 1, 2, 3 or 4.", 'red'))
